FROM node:12.16.3

COPY /app /app
RUN mkdir -p /app/out

WORKDIR /app
# build node
RUN npm install

# build ethereum
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && apt-get install -y build-essential git \
    && add-apt-repository ppa:longsleep/golang-backports \
    && apt-get install -y golang-go \
    && apt-get install -y jq
RUN git clone https://github.com/ethereum/go-ethereum
WORKDIR /go-ethereum
RUN make geth
RUN ln -sf /go-ethereum/build/bin/geth /bin/geth
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN apt-get install bootnode

ENTRYPOINT bash start.sh