apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuer-dapp-deployname
  namespace: recval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuer-dapp
  template:
    metadata:
      labels:
        app: issuer-dapp
    spec:
      containers:
        - name: issuer-dapp
          image: f221267155/issuerdapp:v1
          imagePullPolicy: Never
