apiVersion: apps/v1
kind: Deployment
metadata:
  name: device981-dapp
  namespace: recval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device981-dapp
      component: device-dapp
  template:
    metadata:
      labels:
        app: device981-dapp
        component: device-dapp
    spec:
      containers:
        - name: device-dapp
          image: f221267155/devicedapp:v2
          env:
            - name: TARGET_ORG
              value: "100"
