apiVersion: apps/v1
kind: Deployment
metadata:
  name: device5-dapp
  namespace: recval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device5-dapp
  template:
    metadata:
      labels:
        app: device5-dapp
    spec:
      containers:
        - name: device-dapp
          image: f221267155/devicedapp:v2
          imagePullPolicy: Never
          env:
            - name: TARGET_ORG
              value: "3"
