apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-testnet-miner1
  namespace: recval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner1-service
  template:
    metadata:
      labels:
        app: miner1-service
    spec:
      containers:
        - name: eth-testnet-miner1
          image: f221267155/eth-testnet:v1
          imagePullPolicy: Never
          command:
            - "/bin/bash"
          args:
            - -c
            - |
              filename=$(basename /ethereum/keystore/*)
              account=0x$(jq -r '.address' /ethereum/keystore/$filename)
              geth --metrics --pprof --mine --miner.threads=1 --miner.gasprice=0 --syncmode "full" --networkid ${NETWORK_ID} --bootnodes enode://`bootnode -writeaddress --nodekey=/opt/bootnode/boot.key`@172.17.0.2:30301 --datadir /ethereum  --unlock $account --password /opt/password/password.txt  --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain '*'  --http.api 'admin,eth,net,web3,personal,miner' --nousb --allow-insecure-unlock
          env:
            - name: NETWORK_ID
              valueFrom:
                configMapKeyRef:
                  name: genesis1
                  key: networkid
          imagePullPolicy: Never
          ports:
            - containerPort: 6060
              name: metric-tcp
            - containerPort: 8545
              name: rpc
            - containerPort: 30303
              name: discovery-tcp
              protocol: TCP
            - containerPort: 30303
              name: discovery-udp
              protocol: UDP
          volumeMounts:
            - name: chaindata
              mountPath: "/ethereum"
            - name: genesis
              mountPath: "/opt/genesis"
              readOnly: true
            - name: password
              mountPath: "/opt/password"
              readOnly: true
            - name: bootkey
              mountPath: "/opt/bootnode"
              readOnly: true
      initContainers:
        - name: init
          image: f221267155/eth-testnet:v1
          imagePullPolicy: Never
          command: ["geth"]
          args: ["--datadir=/ethereum", "account", "new", "--password=/opt/password/password.txt"]
          volumeMounts:
            - name: password
              mountPath: "/opt/password"
              readOnly: true
            - name: chaindata
              mountPath: "/ethereum"
        - name: genesis
          image: f221267155/eth-testnet:v1
          imagePullPolicy: Never
          command: ["geth"]
          args: ["--datadir=/ethereum", "init", "/opt/genesis/genesis.json"]
          volumeMounts:
            - name: genesis
              mountPath: /opt/genesis
              readOnly: true
            - name: chaindata
              mountPath: "/ethereum"
      volumes:
        - name: genesis
          configMap:
            name: genesis1
        - name: chaindata
          emptyDir: {}
        - name: password
          secret:
            secretName: password1
        - name: bootkey
          secret:
            secretName: bootkey1
---
kind: Service
apiVersion: v1
metadata:
  name: miner1-service
  namespace: recval
spec:
  # type: NodePort
  selector:
    app: miner1-service
  ports:
    - port: 6060
      targetPort: 6060
      name: metric-tcp
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-tcp
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-udp
      protocol: UDP
