FROM ubuntu:latest

RUN apt-get update -yq \
    && apt-get -yq install curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash \
    && apt-get update -yq \
    && apt-get install nodejs
    # && rm -rf /var/lib/apt/lists/*

COPY /app /app
RUN mkdir -p /app/out

WORKDIR /app
RUN npm install

# ENTRYPOINT bash start.sh

 # Get the Ethereum Stuffs
WORKDIR /
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && apt-get install -y build-essential git \
    && add-apt-repository ppa:longsleep/golang-backports \
    && apt-get install -y golang-go \
    && apt-get install -y jq
RUN git clone https://github.com/ethereum/go-ethereum
WORKDIR /go-ethereum
RUN make geth
RUN ln -sf /go-ethereum/build/bin/geth /bin/geth
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN apt-get install bootnode

RUN rm -rf /var/lib/apt/lists/*