apiVersion: apps/v1
kind: Deployment
metadata:
  name: org100-dapp-deployname
  namespace: recval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org100-dapp-service
  template:
    metadata:
      labels:
        app: org100-dapp-service
    spec:
      containers:
        - name: org-dapp
          image: f221267155/orgdapp:v1
          imagePullPolicy: Never
          env:
            - name: ORG_NAME
              value: "org100-name"
            - name: ORG_DESC
              value: "org100-desc"
            - name: PLANT_NUM
              value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: org100-dapp-service
  namespace: recval
spec:
  type: NodePort
  selector:
    app: org100-dapp-service
  ports:
    - port: 3000
      targetPort: 3000
      name: discovery-tcp
      protocol: TCP
