apiVersion: apps/v1
kind: Deployment
metadata:
  name: org5-dapp-deployname
  namespace: "recval"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org5-dapp-service
  template:
    metadata:
      labels:
        app: org5-dapp-service
    spec:
      containers:
        - name: org-dapp
          image: f221267155/orgdapp:v2
          imagePullPolicy: Never
          command:
            - "/bin/bash"
          env:
            - name: ORG_NAME
              value: "org5-name"
            - name: ORG_DESC
              value: "org5-desc"
            - name: PLANT_NUM
              value: "2"
            - name: ORG_IS_MINER
              value: "false"
          args:
            - -c
            - |
              rpc=http://127.0.0.1:8545
              ws_rpc=http://127.0.0.1:8546
              v=$(jq ".rpc=\"$rpc\" | .ws_rpc=\"$ws_rpc\"" /app/resource/provider.json)
              echo $v > /app/resource/provider.json
              while true
              do
                isSyncing=$(geth attach http://127.0.0.1:8545 -exec "eth.syncing")
                echo node isSyncing: $isSyncing
                if [[ $isSyncing == false ]];
                then
                  echo node is fully synced with other nodes!!
                  break
                fi
                sleep 5
              done

              if [[ $ORG_IS_MINER == "true" ]];
              then
                geth attach http://127.0.0.1:8545 -exec "miner.start(1)"
              fi

              datadir=/ethereum
              filename=$(basename /ethereum/keystore/*)
              account=0x$(jq -r '.address' /ethereum/keystore/$filename)
              password=$(cat /opt/password/password.txt)
              bash /app/start.sh $datadir $account $password
          ports:
            - containerPort: 3000
              name: my-server-tcp
          volumeMounts:
            - name: chaindata
              mountPath: "/ethereum"
            - name: password
              mountPath: "/opt/password"
        - name: org-node
          image: f221267155/eth-testnet:v1
          imagePullPolicy: Never
          command:
            - "/bin/bash"
          args:
            - -c
            - |
              filename=$(basename /ethereum/keystore/*)
              account=0x$(jq -r '.address' /ethereum/keystore/$filename)
              geth --miner.gasprice=0 --syncmode "full" --networkid ${NETWORK_ID} --bootnodes enode://`bootnode -writeaddress --nodekey=/opt/bootnode/boot.key`@172.17.0.2:30301 --datadir /ethereum  --unlock $account --password /opt/password/password.txt  --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain '*' --http.api 'admin,eth,net,web3,personal,miner' --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*' --ws.api 'eth,net,web3' --nousb --allow-insecure-unlock
          env:
            - name: NETWORK_ID
              valueFrom:
                configMapKeyRef:
                  name: genesis1
                  key: networkid
          ports:
            - containerPort: 8545
              name: rpc
            - containerPort: 8546
              name: wsrpc
            - containerPort: 30303
              name: discovery-tcp
              protocol: TCP
            - containerPort: 30303
              name: discovery-udp
              protocol: UDP
          volumeMounts:
            - name: chaindata
              mountPath: "/ethereum"
            - name: genesis
              mountPath: "/opt/genesis"
              readOnly: true
              readOnly: true
            - name: password
              mountPath: "/opt/password"
              readOnly: true
            - name: bootkey
              mountPath: "/opt/bootnode"
              readOnly: true
      initContainers:
        - name: init
          image: f221267155/eth-testnet:v1
          imagePullPolicy: Never
          command: ["geth"]
          args: ["--datadir=/ethereum", "account", "new", "--password=/opt/password/password.txt"]
          volumeMounts:
            - name: password
              mountPath: "/opt/password"
              readOnly: true
            - name: chaindata
              mountPath: "/ethereum"
        - name: genesis
          image: f221267155/eth-testnet:v1
          imagePullPolicy: Never
          command: ["geth"]
          args: ["--datadir=/ethereum", "init", "/opt/genesis/genesis.json"]
          volumeMounts:
            - name: genesis
              mountPath: /opt/genesis
              readOnly: true
            - name: chaindata
              mountPath: "/ethereum"
      volumes:
        - name: genesis
          configMap:
            name: genesis1
        - name: chaindata
          emptyDir: {}
        - name: password
          secret:
            secretName: password1
        - name: bootkey
          secret:
            secretName: bootkey1
---
kind: Service
apiVersion: v1
metadata:
  name: org5-dapp-service
  namespace: "recval"
spec:
  # type: NodePort
  selector:
    app: org5-dapp-service
  ports:
    - port: 3000
      targetPort: 3000
      name: my-server-tcp
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-tcp
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-udp
      protocol: UDP
