apiVersion: apps/v1
kind: Deployment
metadata:
  name: org3-dapp-deployname
  namespace: testrecval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org3-dapp-service
  template:
    metadata:
      labels:
        app: org3-dapp-service
    spec:
      containers:
        - name: org-dapp
          image: f221267155/orgdapp:v1
          imagePullPolicy: Never
          env:
            - name: ORG_NAME
              value: "org3-name"
            - name: ORG_DESC
              value: "org3-desc"
            - name: PLANT_NUM
              value: "2"
---
kind: Service
apiVersion: v1
metadata:
  name: org3-dapp-service
  namespace: testrecval
spec:
  type: NodePort
  selector:
    app: org3-dapp-service
  ports:
    - port: 3000
      targetPort: 3000
      name: discovery-tcp
      protocol: TCP
